[pytest]
addopts =  --browser=chromium --screenshot=only-on-failure --video=retain-on-failure --tracing=retain-on-failure --html=report.html --self-contained-html
#addopts = --headed  --browser=chromium